version: "3.9"

services:
  books-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: books-api-demo
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
